name: Build

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: 'latest'
      is_build:
        type: boolean
        default: true
      is_build_upload:
        type: boolean
        default: true
      is_type_checked:
        type: boolean
        default: true
      is_tested:
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format

      - name: Check linter
        run: npm run lint

      - name: Check types
        if: ${{ inputs.is_build && inputs.is_type_checked }}
        run: npm run ts:check

      - name: Check Tests
        if: ${{ inputs.is_tested }}
        run: npm run test

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          chmod -R 755 $GITHUB_WORKSPACE

      - name: Build
        if: ${{ inputs.is_build }}
        run: npm run build

      - name: 'Upload build artifact'
        if: ${{ inputs.is_build && inputs.is_build_upload }}
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist
